// Auto-generated by mcstory/record.py
const mineflayer = require('mineflayer');
const { pathfinder, Movements, goals } = require('mineflayer-pathfinder');

const characters = ["steve", "villager", "creeper"];
const events = [{"t": 0, "type": "camera", "preset": "wide", "pos": [10, 70, 10], "look_at": [0, 64, 0], "fov": 70}, {"type": "look", "actor": "villager", "xyz": [2, 64, 1], "t": 0.5}, {"type": "look", "actor": "steve", "xyz": [0, 64, 3], "t": 0.5}, {"t": 0, "type": "subtitle", "text": "怪事：村庄正午突然天黑，村民喊末影人偷走了太阳！", "end_t": 3}, {"t": 0.3, "type": "voiceover", "text": "正午十二点，村庄的太阳竟然消失了。", "end_t": 3}, {"t": 3, "type": "camera", "preset": "medium", "pos": [3, 66, 3], "look_at": [0, 64, 0], "fov": 60}, {"type": "look", "actor": "steve", "xyz": [4, 65, 2], "t": 3.5}, {"type": "look", "actor": "villager", "xyz": [6, 64, 0], "t": 3.5}, {"type": "look", "actor": "steve", "xyz": [8, 64, -2], "t": 3.5}, {"t": 3, "type": "subtitle", "text": "追查：铁傀儡一动不动拒绝出手，只留下黑色粒子和被搬走的发光方块。", "end_t": 18}, {"t": 3.3, "type": "voiceover", "text": "史蒂夫沿着屋顶追查，线索全都指向会搬方块的神秘黑影。", "end_t": 18}, {"t": 18, "type": "camera", "preset": "closeup_object", "pos": [1, 64.5, 1], "look_at": [0, 64, 0], "fov": 40}, {"type": "place_block", "actor": "villager", "xyz": [8, 64, -2], "block": "stone", "t": 18.5}, {"type": "look", "actor": "steve", "xyz": [8, 64, -1], "t": 18.5}, {"type": "look", "actor": "creeper", "xyz": [9, 64, -3], "t": 18.5}, {"t": 18, "type": "subtitle", "text": "误导：纸条写着“太阳已被末影人带走”，铁傀儡继续装没看见。", "end_t": 26}, {"t": 18.3, "type": "voiceover", "text": "所有人都以为真凶就是末影人，只有草垛后传来奇怪的嘶嘶声。", "end_t": 26}, {"t": 26, "type": "camera", "preset": "freeze_zoom", "pos": [2, 65, 2], "look_at": [0, 64.5, 0], "fov": 55, "freeze": true, "zoom_to": 50}, {"type": "look", "actor": "creeper", "xyz": [9, 64, -3], "t": 26.5}, {"type": "look", "actor": "steve", "xyz": [8, 64, -1], "t": 26.5}, {"type": "look", "actor": "villager", "xyz": [6, 64, 0], "t": 26.5}, {"t": 26, "type": "subtitle", "text": "反转：不是太阳被偷，是苦力怕用黑旗遮天，想让大家早点睡！", "end_t": 30}, {"t": 26.3, "type": "voiceover", "text": "真相大白：铁傀儡没出手，因为它早看出这只是村庄恶作剧。", "end_t": 30}];
const startTime = Date.now();

// 为每个 character 启一个 bot
const bots = {};
characters.forEach((char, idx) => {
    const bot = mineflayer.createBot({
        host: 'localhost',
        port: 25565,
        username: char + '_bot',
        version: '1.20.4'
    });
    bot.loadPlugin(pathfinder);
    bots[char] = bot;
    
    bot.once('spawn', () => {
        console.log(`bot ${char}_bot spawned`);
        const mcData = require('minecraft-data')(bot.version);
        const movements = new Movements(bot, mcData);
        bot.pathfinder.setMovements(movements);
    });
    
    bot.on('error', err => console.error(`${char}_bot err:`, err.message));
});

// 按时间触发动作
events.forEach(ev => {
    const delayMs = (ev.t || 0) * 1000;
    setTimeout(() => {
        const bot = bots[ev.actor];
        if (!bot || !bot.entity) return;
        try {
            if (ev.type === 'goto') {
                const [x,y,z] = ev.xyz;
                bot.pathfinder.setGoal(new goals.GoalBlock(x, y, z));
            } else if (ev.type === 'look') {
                const [x,y,z] = ev.xyz;
                bot.lookAt({x, y, z});
            }
            console.log(`[t=${ev.t}s] ${ev.actor} ${ev.type}`);
        } catch(e) { console.error('action err:', e.message); }
    }, delayMs);
});

// 30 秒后关闭所有 bot
setTimeout(() => {
    Object.values(bots).forEach(b => b.quit('录制完成'));
    process.exit(0);
}, 32000);
