// Auto-generated by mcstory/record.py
const mineflayer = require('mineflayer');
const { pathfinder, Movements, goals } = require('mineflayer-pathfinder');

const characters = ["steve", "villager"];
const events = [{"t": 0, "type": "camera", "preset": "wide", "pos": [10, 70, 10], "look_at": [0, 64, 0], "fov": 70}, {"t": 0, "type": "subtitle", "text": "我的床呢?", "end_t": 3}, {"t": 0.3, "type": "voiceover", "text": "玩家睁眼, 床位是空地, 火把灭了。", "end_t": 3}, {"t": 3, "type": "camera", "preset": "closeup_object", "pos": [1, 64.5, 1], "look_at": [0, 64, 0], "fov": 40}, {"t": 3, "type": "subtitle", "text": "地图...缺了", "end_t": 6}, {"t": 3.3, "type": "voiceover", "text": "翻出地图, 出生点那块是一片黑。", "end_t": 6}, {"t": 6, "type": "camera", "preset": "medium", "pos": [3, 66, 3], "look_at": [0, 64, 0], "fov": 60}, {"t": 6, "type": "subtitle", "text": "你是谁?", "end_t": 9}, {"t": 6.3, "type": "voiceover", "text": "村民侧身让路, 像是看不见他。", "end_t": 9}, {"t": 9, "type": "camera", "preset": "closeup_face", "pos": [1, 65, 1], "look_at": [0, 65, 0], "fov": 50}, {"t": 9, "type": "subtitle", "text": "新来的?", "end_t": 12}, {"t": 9.3, "type": "voiceover", "text": "村民只丢下一句, 转身就走。", "end_t": 12}, {"t": 12, "type": "camera", "preset": "freeze_zoom", "pos": [2, 65, 2], "look_at": [0, 64.5, 0], "fov": 55, "freeze": true, "zoom_to": 50}, {"t": 12, "type": "subtitle", "text": "你从没出生过", "end_t": 15}, {"t": 12.3, "type": "voiceover", "text": "镜头特写告示: 你从没出生过. 玩家身体开始透明。", "end_t": 15}];
const startTime = Date.now();

// 为每个 character 启一个 bot (错开 4s 避开 Paper connection-throttle)
const bots = {};
const botPromises = [];
characters.forEach((char, idx) => {
  botPromises.push(new Promise((resolve) => {
    setTimeout(() => {
    const bot = mineflayer.createBot({
        host: 'localhost',
        port: 25565,
        username: char + '_bot',
        version: '1.20.4'
    });
    bot.loadPlugin(pathfinder);
    bots[char] = bot;
    
    bot.once('spawn', () => {
        console.log(`bot ${char}_bot spawned`);
        const mcData = require('minecraft-data')(bot.version);
        const movements = new Movements(bot, mcData);
        bot.pathfinder.setMovements(movements);
    });
    
    bot.on('error', err => console.error(`${char}_bot err:`, err.message));
    bot.once('spawn', () => resolve());
    }, idx * 6000);
  }));
});

// Hard timeout: 不管 Promise.all, 50s 后强退
setTimeout(() => { console.log('=== HARD TIMEOUT 50s, exit ==='); process.exit(2); }, 50000);

// 等所有 bot ready 后再开始 timeline 调度
Promise.all(botPromises).then(() => {
  console.log('=== all bots spawned, starting timeline ===');
  events.forEach(ev => {
    const delayMs = (ev.t || 0) * 1000;
    setTimeout(() => {
        const bot = bots[ev.actor];
        if (!bot || !bot.entity) return;
        try {
            if (ev.type === 'goto') {
                const [x,y,z] = ev.xyz;
                bot.pathfinder.setGoal(new goals.GoalBlock(x, y, z));
            } else if (ev.type === 'look') {
                const [x,y,z] = ev.xyz;
                bot.lookAt({x, y, z});
            }
            console.log(`[t=${ev.t}s] ${ev.actor} ${ev.type}`);
        } catch(e) { console.error('action err:', e.message); }
    }, delayMs);
  });
  // 30 秒后关闭所有 bot (从 timeline 启动后算)
  setTimeout(() => {
    Object.values(bots).forEach(b => b.quit('录制完成'));
    process.exit(0);
  }, 32000);
});
