#!/usr/bin/env python3
"""record.py — 接 timeline JSON, 启 mineflayer bot, 按时间触发 MC 命令
注: ReplayMod 录像需 MC 客户端运行, 这步老板做"""
import sys, json, os, subprocess, time
from pathlib import Path

def build_minecraft_commands(timeline):
    """timeline → MC 命令脚本 (server 端跑)
    输出格式: 时间戳 命令 (用 cron-like 调度)"""
    cmds = []
    for ev in timeline["timeline"]:
        t = ev.get("t", 0)
        if ev["type"] == "tellraw":
            # 用 server /tellraw 显示对话气泡
            txt = ev.get("text", "...")
            color = ev.get("color", "white")
            cmds.append((t, f'/tellraw @a {{"text":"{ev["actor"]}: {txt}","color":"{color}"}}'))
        elif ev["type"] == "setblock":
            x,y,z = ev["xyz"]
            cmds.append((t, f'/setblock {x} {y} {z} {ev["block"]}'))
        elif ev["type"] == "particle":
            x,y,z = ev["xyz"]
            cmds.append((t, f'/particle {ev["particle"]} {x} {y} {z} 1 1 1 0.5 30'))
        elif ev["type"] == "subtitle":
            # 用 /title 显示字幕
            cmds.append((t, f'/title @a actionbar {{"text":"{ev["text"]}"}}'))
    return cmds

def build_mineflayer_script(timeline, host="localhost", port=25565):
    """timeline → Node.js mineflayer 脚本 (bot 端跑)"""
    chars = timeline["spawn_chars"]
    events = timeline["timeline"]
    
    # 取角色相关 actions
    actor_events = {}
    for ev in events:
        actor = ev.get("actor")
        if actor and ev["type"] in ("goto", "look", "attack", "use", "place_block"):
            actor_events.setdefault(actor, []).append(ev)
    
    js = f"""// Auto-generated by mcstory/record.py
const mineflayer = require('mineflayer');
const {{ pathfinder, Movements, goals }} = require('mineflayer-pathfinder');

const characters = {json.dumps(chars)};
const events = {json.dumps(events, ensure_ascii=False)};
const startTime = Date.now();

// 为每个 character 启一个 bot (错开 4s 避开 Paper connection-throttle)
const bots = {{}};
const botPromises = [];
characters.forEach((char, idx) => {{
  botPromises.push(new Promise((resolve) => {{
    setTimeout(() => {{
    const bot = mineflayer.createBot({{
        host: '{host}',
        port: {port},
        username: char + '_bot',
        version: '1.20.4'
    }});
    bot.loadPlugin(pathfinder);
    bots[char] = bot;
    
    bot.once('spawn', () => {{
        console.log(`bot ${{char}}_bot spawned`);
        const mcData = require('minecraft-data')(bot.version);
        const movements = new Movements(bot, mcData);
        bot.pathfinder.setMovements(movements);
    }});
    
    bot.on('error', err => console.error(`${{char}}_bot err:`, err.message));
    bot.once('spawn', () => resolve());
    }}, idx * 6000);
  }}));
}});

// Hard timeout: 不管 Promise.all, 50s 后强退
setTimeout(() => {{ console.log('=== HARD TIMEOUT 50s, exit ==='); process.exit(2); }}, 50000);

// 等所有 bot ready 后再开始 timeline 调度
Promise.all(botPromises).then(() => {{
  console.log('=== all bots spawned, starting timeline ===');
  events.forEach(ev => {{
    const delayMs = (ev.t || 0) * 1000;
    setTimeout(() => {{
        const bot = bots[ev.actor];
        if (!bot || !bot.entity) return;
        try {{
            if (ev.type === 'goto') {{
                const [x,y,z] = ev.xyz;
                bot.pathfinder.setGoal(new goals.GoalBlock(x, y, z));
            }} else if (ev.type === 'look') {{
                const [x,y,z] = ev.xyz;
                bot.lookAt({{x, y, z}});
            }}
            console.log(`[t=${{ev.t}}s] ${{ev.actor}} ${{ev.type}}`);
        }} catch(e) {{ console.error('action err:', e.message); }}
    }}, delayMs);
  }});
  // 30 秒后关闭所有 bot (从 timeline 启动后算)
  setTimeout(() => {{
    Object.values(bots).forEach(b => b.quit('录制完成'));
    process.exit(0);
  }}, 32000);
}});
"""
    return js

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("用法: record.py timeline.json"); sys.exit(1)
    timeline = json.load(open(sys.argv[1]))
    in_dir = os.path.dirname(os.path.abspath(sys.argv[1]))

    # 输出 server 命令脚本 (同目录, 固定名字)
    cmds = build_minecraft_commands(timeline)
    cmd_path = os.path.join(in_dir, "server_cmds.txt")
    with open(cmd_path, "w") as f:
        for t, c in sorted(cmds, key=lambda x: x[0]):
            f.write(f"{t:6.2f}\t{c}\n")
    print(f"✓ Server 命令 (调度脚本): {cmd_path}")
    print(f"  共 {len(cmds)} 条命令")
    
    # 输出 mineflayer 脚本
    js = build_mineflayer_script(timeline)
    js_path = os.path.join(in_dir, "bot.js")
    with open(js_path, "w") as f:
        f.write(js)
    print(f"✓ Mineflayer bot 脚本: {js_path}")
    print(f"  spawn {len(timeline['spawn_chars'])} 个 bot")
