// Auto-generated by mcstory/record.py
const mineflayer = require('mineflayer');
const { pathfinder, Movements, goals } = require('mineflayer-pathfinder');

const characters = ["steve", "villager", "iron_golem"];
const events = [{"t": 0, "type": "camera", "preset": "wide", "pos": [10, 70, 10], "look_at": [0, 64, 0], "fov": 70}, {"t": 0, "type": "subtitle", "text": "开庭。", "end_t": 3}, {"t": 0.3, "type": "voiceover", "text": "处决台升起, 铁傀儡看守。", "end_t": 3}, {"t": 3, "type": "camera", "preset": "medium", "pos": [3, 66, 3], "look_at": [0, 64, 0], "fov": 60}, {"t": 3, "type": "subtitle", "text": "押上来。", "end_t": 10}, {"t": 3.3, "type": "voiceover", "text": "村民被推上处决台, 满身泥土。", "end_t": 10}, {"t": 10, "type": "camera", "preset": "closeup_face", "pos": [1, 65, 1], "look_at": [0, 65, 0], "fov": 50}, {"t": 10, "type": "subtitle", "text": "他会说话?", "end_t": 18}, {"t": 10.3, "type": "voiceover", "text": "村民突然开口, 全场寂静。", "end_t": 18}, {"t": 18, "type": "camera", "preset": "closeup_object", "pos": [1, 64.5, 1], "look_at": [0, 64, 0], "fov": 40}, {"t": 18, "type": "subtitle", "text": "别杀我。", "end_t": 26}, {"t": 18.3, "type": "voiceover", "text": "村民颤抖, 玩家举刀停顿。", "end_t": 26}, {"t": 26, "type": "camera", "preset": "freeze_zoom", "pos": [2, 65, 2], "look_at": [0, 64.5, 0], "fov": 55, "freeze": true, "zoom_to": 50}, {"t": 26, "type": "subtitle", "text": "他是上一任服主。", "end_t": 30}, {"t": 26.3, "type": "voiceover", "text": "告示反转, 镜头定格于牌子。", "end_t": 30}];
const startTime = Date.now();

// 为每个 character 启一个 bot (错开 4s 避开 Paper connection-throttle)
const bots = {};
const botPromises = [];
characters.forEach((char, idx) => {
  botPromises.push(new Promise((resolve) => {
    setTimeout(() => {
    const bot = mineflayer.createBot({
        host: 'localhost',
        port: 25565,
        username: char + '_bot',
        version: '1.20.4'
    });
    bot.loadPlugin(pathfinder);
    bots[char] = bot;
    
    bot.once('spawn', () => {
        console.log(`bot ${char}_bot spawned`);
        const mcData = require('minecraft-data')(bot.version);
        const movements = new Movements(bot, mcData);
        bot.pathfinder.setMovements(movements);
    });
    
    bot.on('error', err => console.error(`${char}_bot err:`, err.message));
    bot.once('spawn', () => resolve());
    }, idx * 4000);
  }));
});

// 等所有 bot ready 后再开始 timeline 调度
Promise.all(botPromises).then(() => {
  console.log('=== all bots spawned, starting timeline ===');
  events.forEach(ev => {
    const delayMs = (ev.t || 0) * 1000;
    setTimeout(() => {
        const bot = bots[ev.actor];
        if (!bot || !bot.entity) return;
        try {
            if (ev.type === 'goto') {
                const [x,y,z] = ev.xyz;
                bot.pathfinder.setGoal(new goals.GoalBlock(x, y, z));
            } else if (ev.type === 'look') {
                const [x,y,z] = ev.xyz;
                bot.lookAt({x, y, z});
            }
            console.log(`[t=${ev.t}s] ${ev.actor} ${ev.type}`);
        } catch(e) { console.error('action err:', e.message); }
    }, delayMs);
  });
  // 30 秒后关闭所有 bot (从 timeline 启动后算)
  setTimeout(() => {
    Object.values(bots).forEach(b => b.quit('录制完成'));
    process.exit(0);
  }, 32000);
});
